### ISSUE TITLE
Running on new data

### ISSUE THREAD

**Issue by jacksonloper** [umarov90/DeepFake#1]
I'm hoping to try running deepcellstate on the sci-plex3 data.  I'm not quite sure where to start.  Documentation for the nature of what a `CellData` object needs to provide would be a great help!

**Comment by umarov90** [comment]
One way would be to transform your new data into the same format as the one the code expects (lincs_phase_1_2.tsv in the data folder). 
Otherwise, you will need to replace the parse_data function from CellData, which extracts data and metadata from the tsv file. 
CellData object stores data/metadata and provides specific profiles based on conditions (get_profile_xxxx methods).

**Comment by jacksonloper** [comment]
Ah good idea.  I'll put it in lincs_phase_1_2.tsv format.  It will have to have exactly 978 genes it looks like (see https://github.com/umarov90/DeepCellState/blob/e65c72f255817532e8a8a3afe2138ae270477601/deepfake.py#L62), but that's actually ok.  Thanks!
